[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "B","I"]
exclude = ["constants/imports.py"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = false
line-ending = "lf"